services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    depends_on:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: 9GS9TB4zo6o0f0uWj4Dm
      DB_HOST: bia.c690siqmu7mh.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
  database:
    image: postgres:17.1
    container_name: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=9GS9TB4zo6o0f0uWj4Dm"
      - "POSTGRES_DB=bia"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
